"""
Markdown报告生成器
"""
from typing import List
from .base import BaseReporter, AnalysisResult
from ..analyzer.base import Issue


class MarkdownReporter(BaseReporter):
    """Markdown报告生成器"""
    
    def __init__(self, config=None):
        super().__init__(config)
    
    @property
    def name(self) -> str:
        return "markdown"
    
    @property
    def extension(self) -> str:
        return "md"
    
    def generate(self, result: AnalysisResult) -> str:
        """生成Markdown报告"""
        lines = []
        
        # 标题
        lines.append("# 🔍 CodeReview-AI 报告")
        lines.append("")
        
        # 摘要
        lines.append("## 📊 分析摘要")
        lines.append("")
        lines.append(f"- **分析文件数**: {len(result.files_analyzed)}")
        lines.append(f"- **分析耗时**: {result.get_duration():.2f}秒")
        lines.append("")
        
        # 问题统计
        lines.append("## 📈 问题统计")
        lines.append("")
        
        counts = result.get_issue_counts()
        
        lines.append("| 严重程度 | 数量 |")
        lines.append("|----------|------|")
        lines.append(f"| 🔴 Critical | {counts['critical']} |")
        lines.append(f"| 🟠 High | {counts['high']} |")
        lines.append(f"| 🟡 Medium | {counts['medium']} |")
        lines.append(f"| 🔵 Low | {counts['low']} |")
        lines.append(f"| ⚪ Info | {counts['info']} |")
        lines.append(f"| **总计** | **{counts['total']}** |")
        lines.append("")
        
        # 问题详情
        if result.issues:
            lines.append("## 📝 问题详情")
            lines.append("")
            
            # 按文件分组
            issues_by_file = result.get_issues_by_file()
            
            for file_path, issues in sorted(issues_by_file.items()):
                lines.append(f"### {file_path}")
                lines.append("")
                
                # 按严重程度排序
                sorted_issues = sorted(issues, key=lambda i: i.severity.priority())
                
                for issue in sorted_issues:
                    lines.extend(self._format_issue(issue))
                    lines.append("")
        
        # AI审查结果
        if result.ai_review:
            lines.append("## 🤖 AI 审查结果")
            lines.append("")
            lines.append(f"**代码评分**: {result.ai_review.score}/100")
            lines.append("")
            
            if result.ai_review.summary:
                lines.append("### 总体评价")
                lines.append("")
                lines.append(result.ai_review.summary)
                lines.append("")
            
            if result.ai_review.strengths:
                lines.append("### ✅ 代码优点")
                lines.append("")
                for strength in result.ai_review.strengths:
                    lines.append(f"- {strength}")
                lines.append("")
            
            if result.ai_review.improvements:
                lines.append("### 💡 改进建议")
                lines.append("")
                for improvement in result.ai_review.improvements:
                    lines.append(f"- {improvement}")
                lines.append("")
            
            if result.ai_review.comments:
                lines.append("### 📌 AI 详细评论")
                lines.append("")
                
                for comment in result.ai_review.comments:
                    lines.append(f"**[{comment.severity.value.upper()}]** {comment.category}")
                    lines.append("")
                    lines.append(comment.message)
                    if comment.suggestion:
                        lines.append("")
                        lines.append(f"**建议**: {comment.suggestion}")
                    if comment.code_example:
                        lines.append("")
                        lines.append("```")
                        lines.append(comment.code_example)
                        lines.append("```")
                    lines.append("")
                    lines.append("---")
                    lines.append("")
        
        # 页脚
        lines.append("---")
        lines.append("")
        lines.append("*Generated by CodeReview-AI*")
        
        return "\n".join(lines)
    
    def _format_issue(self, issue: Issue) -> List[str]:
        """格式化单个问题"""
        lines = []
        
        severity_emoji = {
            "critical": "🔴",
            "high": "🟠",
            "medium": "🟡",
            "low": "🔵",
            "info": "⚪",
        }.get(issue.severity.value, "⚪")
        
        # 问题标题
        lines.append(f"#### {severity_emoji} [{issue.severity.value.upper()}] {issue.rule_name}")
        lines.append("")
        
        # 位置
        if issue.line > 0:
            lines.append(f"**位置**: `{issue.file_path}:{issue.line}`")
        else:
            lines.append(f"**文件**: `{issue.file_path}`")
        lines.append("")
        
        # 消息
        lines.append(f"**问题**: {issue.message}")
        lines.append("")
        
        # 描述
        if issue.description:
            lines.append(f"**描述**: {issue.description}")
            lines.append("")
        
        # 建议
        if issue.suggestion:
            lines.append(f"**建议**: {issue.suggestion}")
            lines.append("")
        
        # 代码片段
        if issue.code_snippet:
            lines.append("**代码片段**:")
            lines.append("```python")
            lines.append(issue.code_snippet)
            lines.append("```")
        
        return lines
